trigger:
- master

pool:
  vmImage: vs2017-win2016

steps:
- checkout: self
  clean: all
  fetchDepth: 1
- task: DownloadPipelineArtifact@0
  inputs:
    artifactName: corefx-s4u
    pipelineId: 17
    targetPath: $(System.DefaultWorkingDirectory)
- script: dotnet publish -c Release -f netcoreapp2.2 -r win10-x64 --self-contained true
  workingDirectory: src/OAKProxy
  displayName: Build
