trigger:
- master

pool:
  vmImage: vs2017-win2016

steps:
- checkout: self
  clean: all
  fetchDepth: 1
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'src/OAKProxy/*.csproj'
- script: dotnet publish -c Release -f netcoreapp2.2 -r win10-x64 --self-contained true --no-restore
  workingDirectory: src/OAKProxy
  displayName: Build
