apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oakproxy.fullname" . }}
  labels:
{{ include "oakproxy.labels" . | indent 4 }}
binaryData:
  keystorecert.pfx: {{ required "A PKCS12 certificate for key storage is required." .Values.keyStorage.certificate }}
data:
  oakproxy.yml: |
{{ required "An OAKProxy configuration file is required." .Values.oakproxyConfiguration | indent 4 }}
