apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oakproxy.fullname" . }}
  labels:
{{ include "oakproxy.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ required "The storage class name for key storage is required."  .Values.keyStorage.storageClass }}
  resources:
    requests:
      storage: 1Gi
