apiVersion: v1
kind: Service
metadata:
  name: {{ include "oakproxy.fullname" . }}
  labels:
{{ include "oakproxy.labels" . | indent 4 }}
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "oakproxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
